/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_server;

import javax.swing.JOptionPane;
import main_server.socketServer.server_fonction.ClientsServerSocketInit;

/**
 *
 * @author RainAlex
 */
public class DBLogin extends javax.swing.JFrame {

    Server main_server;

    /**
     * Creates new form DBLogin
     */
    public DBLogin() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        dbField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        validerBtn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        tcpField = new javax.swing.JTextField();
        hostField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONNEXION AU SERVEUR");

        portField.setText("PORT BD");
        portField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                portFieldMouseClicked(evt);
            }
        });
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });

        dbField.setText("NOM DE LA BD");
        dbField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbFieldMouseClicked(evt);
            }
        });
        dbField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbFieldActionPerformed(evt);
            }
        });

        userField.setText("USER BD");
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFieldMouseClicked(evt);
            }
        });

        validerBtn.setText("VALIDER");
        validerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerBtnMouseClicked(evt);
            }
        });
        validerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtnActionPerformed(evt);
            }
        });

        jPasswordField1.setText("PASSWORD");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        tcpField.setText("PORT TCP");
        tcpField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcpFieldMouseClicked(evt);
            }
        });
        tcpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpFieldActionPerformed(evt);
            }
        });

        hostField.setText("HOST");
        hostField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1)
                    .addComponent(userField)
                    .addComponent(dbField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(portField))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tcpField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(hostField))
                    .addComponent(validerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerBtn))
                .addGap(16, 16, 16)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, "card2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CONNEXION AU SERVEUR FAIT !");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card3");

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    private void dbFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbFieldActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dbFieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void portFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portFieldMouseClicked
	portField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldMouseClicked

    private void dbFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbFieldMouseClicked
	dbField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_dbFieldMouseClicked

    private void userFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFieldMouseClicked
	userField.setText("");
    }//GEN-LAST:event_userFieldMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
	jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void validerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerBtnMouseClicked
	String port = portField.getText();
	String db = dbField.getText();
	String user = userField.getText();
	String pwd = new String(jPasswordField1.getPassword());
	String host = hostField.getText();
	int portTCP = Integer.parseInt(tcpField.getText());
	if ((port.compareTo("") != 0) && ((host.compareTo("") != 0) && (tcpField.getText().compareTo("") != 0))) {
	    if ((user.compareTo("") != 0) && (db.compareTo("") != 0)) {
		Server main_server = new Server(port, db, user, pwd);
		if (main_server.getConnect().isConnected()){
		    ClientsServerSocketInit ts = new ClientsServerSocketInit(host, portTCP, main_server);
		    ts.open();
		    jPanel2.removeAll();
		    jPanel2.add(jPanel3);
		    jPanel2.repaint();
		    jPanel2.revalidate();
		} else {
		    JOptionPane.showMessageDialog(null,
		    "Erreur des identifiants",
		    "ERROR !",
		    JOptionPane.ERROR_MESSAGE);
		}
	    }
	}
    }//GEN-LAST:event_validerBtnMouseClicked

    private void validerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerBtnActionPerformed

    private void tcpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcpFieldActionPerformed

    private void tcpFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcpFieldMouseClicked
        tcpField.setText("");
    }//GEN-LAST:event_tcpFieldMouseClicked

    private void hostFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostFieldMouseClicked
        hostField.setText("");
    }//GEN-LAST:event_hostFieldMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(DBLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(DBLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(DBLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(DBLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new DBLogin().setVisible(true);
	    }
	});

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbField;
    private javax.swing.JTextField hostField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField portField;
    private javax.swing.JTextField tcpField;
    private javax.swing.JTextField userField;
    private javax.swing.JButton validerBtn;
    // End of variables declaration//GEN-END:variables
}
